using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class SC_bin_button : MonoBehaviour
{
    public Button button;
    public SC_slots SC_slots;
    public Text text;

    public int actual_funny_text = 0;
    string[] funny_texts = new string[]
{
//#1
"Behold, the endless abyss of cosmic trash.",
"From Earth to the edges of infinity, your garbage reigns supreme.",
"Space debris: the gift that keeps on giving.",
"The cosmos is now littered with your discarded belongings.",
"The infinite cosmos now bears your discarded items.",
"The stars now shine upon your waste.",
"Your debris has found a new home among the stars.",
"Your discarded items are now cosmic relics.",
"Your garbage has now become a part of the cosmic ecosystem.",
"Your garbage has now become an inseparable part of the universe.",
"Your garbage is floating in the void, forever immortalized.",
"Your garbage is now a permanent fixture in the cosmos.",
"Your junk has now joined the celestial clutter.",
"Your junk is now interstellar.",
"Your litter has become a permanent fixture in the cosmos.",
"Your litter is now a part of the universe's legacy.",
"Your refuse has taken its place among the stars.",
"Your refuse has now become a part of the universe's history.",
"Your trash has embarked on an intergalactic adventure.",
"Your trash has traveled farther than any human ever will.",
"Your trash heap now spans the universe.",
"Your waste has gone where no trash has gone before.",
"Your waste has now become cosmic debris.",
"Your waste has now become a part of the universe's history.",
"Your waste has now become a part of the cosmic ecosystem.",
"Your waste is now immortalized in the stars.",
"You've added a new dimension to the universe: your garbage.",
"You've contributed to the infinite garbage dump in the sky.",
"You've created a celestial junkyard.",
"You've given the universe a gift it didn't want: your garbage.",
"You've left a trail of trash across the universe.",
"You've left your mark on the universe with your garbage.",
"You've made the universe a little dirtier with your trash.",
"You've made your mark on the universe with your trash.",
"You've unleashed your trash upon the cosmos.",
"Space: the final frontier for your unwanted possessions.",
"The universe now bears witness to your refuse.",
"The universe will never forget the impact of your trash.",
"The vast expanse of space now bears your refuse.",
"The universe now carries the burden of your garbage.",
"The universe now carries the weight of your discarded belongings.",
"The universe now bears the weight of your discarded belongings.",
"The universe now bears the weight of your garbage.",
"You've turned the universe into your personal trash can.",
"Your garbage is now a permanent resident of the universe.",
"Your litter now roams the cosmos.",
"Your trash now pollutes the cosmic landscape.",
"Your waste has taken over the universe.",
"Your discarded items now float aimlessly through the cosmos.",
//#2
"Your trash has left a lasting impression on the cosmos.",
"Your garbage has found a new home among the stars, and it's not leaving anytime soon.",
"Your waste has added a new layer of complexity to the universe.",
"You've given the universe a new challenge to overcome: your waste.",
"The universe now hosts a galactic landfill, thanks to you.",
"Your trash has become a part of the universe's fabric.",
"Your garbage has become a part of the universe's DNA.",
"Your discarded items are now cosmic orphans, lost in the vastness of space.",
"The cosmos is now a little bit dirtier, thanks to your litter.",
"Your waste has become the universe's problem.",
"Your trash is now a permanent fixture in the celestial landscape.",
"Your garbage has now become a cosmic legend.",
"Your discarded items have achieved interstellar fame.",
"Your litter now floats through the cosmos, a testament to human waste.",
"Your waste has taken on a life of its own, roaming the universe without end.",
"Your trash has transcended the boundaries of Earth and entered the infinite expanse of space.",
"Your garbage has joined the ranks of the universe's most notorious villains.",
"The universe now carries the burden of your waste, forever.",
"Your litter has become an eternal reminder of human excess.",
"Your trash is now a permanent reminder of our impact on the universe.",
"Your discarded items have become a part of the cosmic history book.",
"Your waste has become a permanent part of the universe's narrative.",
"Your garbage is now a universal symbol of human negligence.",
"The cosmos now bears the scars of your waste.",
"Your trash has become a cosmic anomaly.",
"Your litter is now a part of the universe's story.",
"Your waste has become a part of the universe's mythos.",
"Your garbage has become a part of the cosmic legacy.",
"The universe now knows your name, and it's not a good thing.",
"Your trash has become a cosmic mystery, floating through space without purpose.",
"Your discarded items have become a part of the cosmic tapestry.",
"Your waste has become a part of the cosmic orchestra, adding a new note to the song of the universe.",
"Your garbage is now a part of the cosmic ballet.",
"Your litter has become a cosmic tragedy.",
"Your waste has become a cosmic comedy.",
"Your trash has become a cosmic horror story.",
"The universe now bears the brunt of your negligence.",
"Your garbage has become a cosmic anomaly, a puzzle for future generations to solve.",
"Your litter has become a cosmic riddle, a mystery waiting to be unraveled.",
"Your waste has become a cosmic conundrum, a puzzle with no clear solution.",
"Your trash has become a cosmic enigma, a question mark in the vastness of space.",
"Your garbage has become a cosmic paradox, a contradiction that defies explanation.",
"Your discarded items have become a cosmic puzzle, a mystery waiting to be solved.",
"Your waste has become a cosmic marvel, a wonder of the universe.",
"Your litter has become a cosmic spectacle, a sight to behold in the depths of space.",
"Your trash has become a cosmic phenomenon, a spectacle that defies explanation.",
"Your garbage has become a cosmic oddity, a quirk of the universe.",
"The universe now carries the weight of your neglect, a burden that will never be lifted.",
"Your waste has become a cosmic tragedy, a story of human excess and neglect.",
"Your litter has become a cosmic epic, a tale of human folly and hubris.",
"Your garbage has become a cosmic legend, a story that will be told for eons to come.",
"Your discarded items have become a cosmic saga, a story with no end in sight.",
//#3
"This game had no garbage collector for such a long time.",
"It might have been a bit radioacive. Who cares!",
"You've broken a gift from Kamiloso.",
//#4
"Your discarded items just threw a little farewell party. They'll be fine!",
"Who needs a museum when you have our Junkyard? A treasure trove of... well, junk!",
"Thank you for the donation! Remember, one player's trash is another player's 'meh.'",
"This Junkyard has seen it all, from rusty blasters to malfunctioning teleporters. Quite the showcase!",
"Hey, at least you're keeping the space garbage collectors in business.",
"Your discarded items have formed a support group. They're coping with rejection.",
"Some of these items may look broken, but they're just going through an 'aesthetic phase.'",
"Your junk has taken up residence here, hoping for a second chance at adventure!",
"Don't worry, we'll give your items a second life... or at least a second-hand.",
"One person's discarded junk is another person's... well, you get the idea.",
"Your discarded items just waved goodbye. Maybe they'll meet again in another life... or sequel.",
"In the vast cosmos, your discarded items found solace in our Junkyard.",
"Your junk has formed a 'Trash-n-Treasure' alliance. Don't underestimate the treasure part!",
"Thanks for making our Junkyard a little more interesting!",
"Your items may not be the most sought-after, but they still deserve their spot in the cosmic dump.",
"Junkyard rule #42: Everything finds a place... even if it's a place of exile.",
"If only your items could talk, they'd have some wild stories to share!",
"Your discarded items are secretly planning a 'Great Escape.' They might need a spaceship, though.",
"Think of it this way: you're just helping the universe declutter!",
"Your items have joined the ranks of legendary space debris.",
"We've seen it all, from floating space boots to half-eaten cosmic sandwiches.",
"One small step for your junk, one giant leap for our Junkyard.",
"The Junkyard welcomes your items with open... garbage disposals.",
"Your items are having a blast, quite literally. They're playing with space grenades.",
"Some might call it a dump, but we prefer 'cosmic curio emporium.'",
"Don't worry, even space trash deserves a place in the stars.",
"Your discarded items are like asteroids - still floating out there, waiting for their destiny.",
"Your items just had a brainstorming session. They're trying to invent 'recycling' in space.",
"Space debris never looked so... junk-tastic!",
"Your items are blending in perfectly with the cosmic chaos. Kudos to you!",
"We're turning your items into cosmic conversation starters!",
"Remember, even in space, one person's junk is another person's treasure. Or not.",
"The Junkyard is like a cosmic magnet for eclectic oddities. Your items fit right in!",
"Who needs an inventory when you can have a 'universal recycling center'?",
"Your discarded items are discussing their dreams of space exploration. They're quite ambitious.",
"You've made our Junkyard a bit more... charming.",
"Just think, somewhere in the universe, your items are appreciated... or at least tolerated.",
"Your items are sparking friendships with other space oddities.",
"Your junk just asked if it could start a band. It's got the rhythm, but not the tune.",
"Your discarded items have discovered the true meaning of 'space oddity.'",
"We're not saying your items are special, but they are definitely... unique.",
"In space, even the oddest items find their place.",
"Your items have formed a club called 'The Reject Rogues.' They're quite proud of it.",
"Your discarded items are practicing their best space yoga poses. They're reaching for the stars.",
"Your junk just challenged the asteroid belt to a space race. Odds are not in its favor.",
"Your items are now honorary members of the 'Cosmic Clutter Crew.'",
"One small toss for you, one giant mess for our Junkyard.",
"Your junk just set a new record for the most dramatic entrance to our Junkyard. Bravo!",
"Your discarded items have formed an alliance with the comet tail community. They're chasing tails together!"
};

    void Update()
    {
        button.interactable =  (SC_slots.BackpackY[16]>0);
    }
    public void UpdateText()
    {
        int old_text = actual_funny_text;
        do{ actual_funny_text = UnityEngine.Random.Range(0,funny_texts.Length); }while(actual_funny_text==old_text);
        text.text = funny_texts[actual_funny_text];
    }
}
